apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcv-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/vanilla"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcv-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce


### FORGE

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mcf-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/forge"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcf-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce