apiVersion: v1
kind: ConfigMap
metadata:
  name: mods-map
data:
  mods.txt: |
    https://cdn.modrinth.com/data/aC3cM3Vq/versions/9IcJV4UJ/MouseTweaks-forge-mc1.21-2.26.jar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      mc: web
  template:
    metadata:
      labels:
        mc: web
    spec:
      volumes:
        - name: mc-pv-storage
          persistentVolumeClaim:
            claimName: mc-pvc
        - name: mods-volume
          configMap:
            name: mods-map
      containers:
        - name: mc-server
          image: itzg/minecraft-server
          imagePullPolicy: Never
          env:
            - name: EULA
              value: "TRUE"
            - name: MODS_FILE
              value: "mods.txt"
            # - name: VERSION
            #   value: 1.15.2
            - name: REMOVE_OLD_MODS
              value: "true"
            - name: TYPE
              value: FORGE
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - mountPath: "/data"
              name: mc-pv-storage
            - mountPath: /data/mods.txt
              subPath: mods.txt
              name: mods-volume

---
apiVersion: v1
kind: Service
metadata:
  name: mc-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    mc: web
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30065


## fix rcon later

---
apiVersion: v1
kind: Service
metadata:
  name: mc-rcon
  namespace: default
spec:
  type: NodePort
  selector:
    mc: web
  ports:
    - port: 25575
      targetPort: 25575
      nodePort: 30075