apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      mc: web
  template:
    metadata:
      labels:
        mc: web
    spec:
      volumes:
        - name: mc-pv-storage
          persistentVolumeClaim:
            claimName: mc-pvc
      containers:
        - name: mc-server
          image: itzg/minecraft-server
          imagePullPolicy: Never
          env:
            - name: EULA
              value: "TRUE"
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - mountPath: "/data"
              name: mc-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: mc-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    mc: web
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30065
---
apiVersion: v1
kind: Service
metadata:
  name: mc-rcon
  namespace: default
spec:
  type: NodePort
  selector:
    mc: web
  ports:
    - port: 25575
      targetPort: 25575
      nodePort: 30075